- hosts: local
  sudo: yes
  roles:
    - common
    - java
    - nginx
    - php
    - hhvm
    - mysql
    - nodejs
    - elastic
    - rabbitmq
    - redis
    - neo4j
    - development
    - projects
  vars_files:
    - group_vars/dev.yml
    - group_vars/dev.local.yml
